# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gravtools/gui/dialog_setup_data.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_setup_data(object):
    def setupUi(self, Dialog_setup_data):
        Dialog_setup_data.setObjectName("Dialog_setup_data")
        Dialog_setup_data.resize(512, 249)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog_setup_data)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox_drift_ref_epoch_active_obs_only = QtWidgets.QCheckBox(Dialog_setup_data)
        self.checkBox_drift_ref_epoch_active_obs_only.setObjectName("checkBox_drift_ref_epoch_active_obs_only")
        self.verticalLayout_3.addWidget(self.checkBox_drift_ref_epoch_active_obs_only)
        self.groupBox_computation_method = QtWidgets.QGroupBox(Dialog_setup_data)
        self.groupBox_computation_method.setObjectName("groupBox_computation_method")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_computation_method)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_variance_weighted_mean = QtWidgets.QRadioButton(self.groupBox_computation_method)
        self.radioButton_variance_weighted_mean.setChecked(True)
        self.radioButton_variance_weighted_mean.setObjectName("radioButton_variance_weighted_mean")
        self.buttonGroup_computation_method = QtWidgets.QButtonGroup(Dialog_setup_data)
        self.buttonGroup_computation_method.setObjectName("buttonGroup_computation_method")
        self.buttonGroup_computation_method.addButton(self.radioButton_variance_weighted_mean)
        self.verticalLayout.addWidget(self.radioButton_variance_weighted_mean)
        self.radioButton_individual_obs = QtWidgets.QRadioButton(self.groupBox_computation_method)
        self.radioButton_individual_obs.setObjectName("radioButton_individual_obs")
        self.buttonGroup_computation_method.addButton(self.radioButton_individual_obs)
        self.verticalLayout.addWidget(self.radioButton_individual_obs)
        self.verticalLayout_3.addWidget(self.groupBox_computation_method)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)

        self.retranslateUi(Dialog_setup_data)
        QtCore.QMetaObject.connectSlotsByName(Dialog_setup_data)

    def retranslateUi(self, Dialog_setup_data):
        _translate = QtCore.QCoreApplication.translate
        Dialog_setup_data.setWindowTitle(_translate("Dialog_setup_data", "Setup data options"))
        self.checkBox_drift_ref_epoch_active_obs_only.setToolTip(_translate("Dialog_setup_data", "Consider only active observations in the determination of the drift polynomial reference epoch(s)."))
        self.checkBox_drift_ref_epoch_active_obs_only.setText(_translate("Dialog_setup_data", "Consider only active observations for the reference epoch"))
        self.groupBox_computation_method.setToolTip(_translate("Dialog_setup_data", "<html><head/><body><p>Select the method for the computation of setup observations.</p></body></html>"))
        self.groupBox_computation_method.setTitle(_translate("Dialog_setup_data", "Setup data computation method"))
        self.radioButton_variance_weighted_mean.setToolTip(_translate("Dialog_setup_data", "<html><head/><body><p>Computa setup observations as the variance weighted mean ob all consecutive observations within one setup. This is the default option for the adjustment of gravity surveys comprising multiple stations or the estimatuion of vertical gravity gradients.</p></body></html>"))
        self.radioButton_variance_weighted_mean.setText(_translate("Dialog_setup_data", "Variance weighted mean"))
        self.radioButton_individual_obs.setToolTip(_translate("Dialog_setup_data", "<html><head/><body><p>Trest each individual observation as setup observation, i.e. do aggregate individual observations at all. This option may be used for analysing  stationary long-term observations at a single station, e.g. for the analysis of tides of the instrument\'s drift behaviour.</p></body></html>"))
        self.radioButton_individual_obs.setText(_translate("Dialog_setup_data", "Individual observations"))
