# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gravtools/gui/dialog_calc_drift.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_calculate_drift(object):
    def setupUi(self, Dialog_calculate_drift):
        Dialog_calculate_drift.setObjectName("Dialog_calculate_drift")
        Dialog_calculate_drift.resize(1087, 646)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog_calculate_drift)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_data_selection = QtWidgets.QGroupBox(Dialog_calculate_drift)
        self.groupBox_data_selection.setObjectName("groupBox_data_selection")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_data_selection)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_survey = QtWidgets.QLabel(self.groupBox_data_selection)
        self.label_survey.setObjectName("label_survey")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_survey)
        self.comboBox_survey = QtWidgets.QComboBox(self.groupBox_data_selection)
        self.comboBox_survey.setObjectName("comboBox_survey")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_survey)
        self.label_station = QtWidgets.QLabel(self.groupBox_data_selection)
        self.label_station.setObjectName("label_station")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_station)
        self.comboBox_station = QtWidgets.QComboBox(self.groupBox_data_selection)
        self.comboBox_station.setObjectName("comboBox_station")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_station)
        self.verticalLayout_4.addLayout(self.formLayout)
        self.checkBox_multiple_setups_only = QtWidgets.QCheckBox(self.groupBox_data_selection)
        self.checkBox_multiple_setups_only.setChecked(True)
        self.checkBox_multiple_setups_only.setObjectName("checkBox_multiple_setups_only")
        self.verticalLayout_4.addWidget(self.checkBox_multiple_setups_only)
        self.checkBox_active_obs_only = QtWidgets.QCheckBox(self.groupBox_data_selection)
        self.checkBox_active_obs_only.setChecked(True)
        self.checkBox_active_obs_only.setObjectName("checkBox_active_obs_only")
        self.verticalLayout_4.addWidget(self.checkBox_active_obs_only)
        self.verticalLayout.addWidget(self.groupBox_data_selection)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.groupBox_parameters = QtWidgets.QGroupBox(Dialog_calculate_drift)
        self.groupBox_parameters.setObjectName("groupBox_parameters")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_parameters)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_degree = QtWidgets.QLabel(self.groupBox_parameters)
        self.label_degree.setObjectName("label_degree")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_degree)
        self.spinBox_degree = QtWidgets.QSpinBox(self.groupBox_parameters)
        self.spinBox_degree.setMinimum(1)
        self.spinBox_degree.setMaximum(3)
        self.spinBox_degree.setObjectName("spinBox_degree")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_degree)
        self.label_method = QtWidgets.QLabel(self.groupBox_parameters)
        self.label_method.setObjectName("label_method")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_method)
        self.comboBox_method = QtWidgets.QComboBox(self.groupBox_parameters)
        self.comboBox_method.setObjectName("comboBox_method")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_method)
        self.label_min_no_obs = QtWidgets.QLabel(self.groupBox_parameters)
        self.label_min_no_obs.setObjectName("label_min_no_obs")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_min_no_obs)
        self.spinBox_min_no_obs = QtWidgets.QSpinBox(self.groupBox_parameters)
        self.spinBox_min_no_obs.setMinimum(1)
        self.spinBox_min_no_obs.setProperty("value", 2)
        self.spinBox_min_no_obs.setObjectName("spinBox_min_no_obs")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBox_min_no_obs)
        self.horizontalLayout.addWidget(self.groupBox_parameters)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.graphicsLayoutWidget_drift_plot = GraphicsLayoutWidget(Dialog_calculate_drift)
        self.graphicsLayoutWidget_drift_plot.setObjectName("graphicsLayoutWidget_drift_plot")
        self.verticalLayout_2.addWidget(self.graphicsLayoutWidget_drift_plot)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_calculate_drift)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(Dialog_calculate_drift)
        self.buttonBox.accepted.connect(Dialog_calculate_drift.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_calculate_drift.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_calculate_drift)

    def retranslateUi(self, Dialog_calculate_drift):
        _translate = QtCore.QCoreApplication.translate
        Dialog_calculate_drift.setWindowTitle(_translate("Dialog_calculate_drift", "Calculate drift"))
        self.groupBox_data_selection.setTitle(_translate("Dialog_calculate_drift", "Data selection"))
        self.label_survey.setText(_translate("Dialog_calculate_drift", "Survey"))
        self.label_station.setText(_translate("Dialog_calculate_drift", "Station"))
        self.checkBox_multiple_setups_only.setText(_translate("Dialog_calculate_drift", "Stations with multiple setups only"))
        self.checkBox_active_obs_only.setText(_translate("Dialog_calculate_drift", "Only consider active observations"))
        self.groupBox_parameters.setTitle(_translate("Dialog_calculate_drift", "Parameters"))
        self.label_degree.setText(_translate("Dialog_calculate_drift", "Poly. degree"))
        self.label_method.setText(_translate("Dialog_calculate_drift", "Drift calc. method"))
        self.label_min_no_obs.setToolTip(_translate("Dialog_calculate_drift", "<html><head/><body><p>Minimum number of observations required to fit a drift polynomial.</p></body></html>"))
        self.label_min_no_obs.setText(_translate("Dialog_calculate_drift", "Min. n/o observations"))
        self.spinBox_min_no_obs.setToolTip(_translate("Dialog_calculate_drift", "<html><head/><body><p>Minimum number of observations required to fit a drift polynomial.</p></body></html>"))
from pyqtgraph import GraphicsLayoutWidget
