# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gravtools/gui/dialog_load_cg6_obs_files.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogLoadCg6ObservationFiles(object):
    def setupUi(self, DialogLoadCg6ObservationFiles):
        DialogLoadCg6ObservationFiles.setObjectName("DialogLoadCg6ObservationFiles")
        DialogLoadCg6ObservationFiles.resize(699, 547)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DialogLoadCg6ObservationFiles)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(DialogLoadCg6ObservationFiles)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.comboBox_format_selection = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_format_selection.setObjectName("comboBox_format_selection")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.comboBox_format_selection)
        self.label_format_selection = QtWidgets.QLabel(self.groupBox)
        self.label_format_selection.setObjectName("label_format_selection")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_format_selection)
        self.spinBox_dt_sec = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_dt_sec.setEnabled(False)
        self.spinBox_dt_sec.setMaximum(9999)
        self.spinBox_dt_sec.setProperty("value", 600)
        self.spinBox_dt_sec.setObjectName("spinBox_dt_sec")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.spinBox_dt_sec)
        self.label_dt_sec = QtWidgets.QLabel(self.groupBox)
        self.label_dt_sec.setEnabled(False)
        self.label_dt_sec.setObjectName("label_dt_sec")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_dt_sec)
        self.checkBox_use_dt = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_use_dt.setText("")
        self.checkBox_use_dt.setObjectName("checkBox_use_dt")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.checkBox_use_dt)
        self.label_use_dt = QtWidgets.QLabel(self.groupBox)
        self.label_use_dt.setObjectName("label_use_dt")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_use_dt)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_format_description = QtWidgets.QLabel(self.groupBox)
        self.label_format_description.setText("")
        self.label_format_description.setWordWrap(True)
        self.label_format_description.setObjectName("label_format_description")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_format_description)
        self.verticalLayout.addLayout(self.formLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_select_files = QtWidgets.QPushButton(DialogLoadCg6ObservationFiles)
        self.pushButton_select_files.setObjectName("pushButton_select_files")
        self.horizontalLayout.addWidget(self.pushButton_select_files)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.listWidget_open_files = QtWidgets.QListWidget(DialogLoadCg6ObservationFiles)
        self.listWidget_open_files.setObjectName("listWidget_open_files")
        self.verticalLayout_2.addWidget(self.listWidget_open_files)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_clear_list = QtWidgets.QPushButton(DialogLoadCg6ObservationFiles)
        self.pushButton_clear_list.setObjectName("pushButton_clear_list")
        self.horizontalLayout_2.addWidget(self.pushButton_clear_list)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogLoadCg6ObservationFiles)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(DialogLoadCg6ObservationFiles)
        self.buttonBox.accepted.connect(DialogLoadCg6ObservationFiles.accept) # type: ignore
        self.buttonBox.rejected.connect(DialogLoadCg6ObservationFiles.reject) # type: ignore
        self.checkBox_use_dt.toggled['bool'].connect(self.spinBox_dt_sec.setEnabled) # type: ignore
        self.checkBox_use_dt.toggled['bool'].connect(self.label_use_dt.setEnabled) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogLoadCg6ObservationFiles)

    def retranslateUi(self, DialogLoadCg6ObservationFiles):
        _translate = QtCore.QCoreApplication.translate
        DialogLoadCg6ObservationFiles.setWindowTitle(_translate("DialogLoadCg6ObservationFiles", "Load CG-6 observation files"))
        self.groupBox.setTitle(_translate("DialogLoadCg6ObservationFiles", "Options"))
        self.label_format_selection.setText(_translate("DialogLoadCg6ObservationFiles", "CG-6 observation file format"))
        self.label_dt_sec.setText(_translate("DialogLoadCg6ObservationFiles", "Minimum time gap to between setups [sec]"))
        self.label_use_dt.setText(_translate("DialogLoadCg6ObservationFiles", "Separate consecutive observations into different setups based an a time gap"))
        self.label.setText(_translate("DialogLoadCg6ObservationFiles", "Format description"))
        self.pushButton_select_files.setText(_translate("DialogLoadCg6ObservationFiles", "Open files"))
        self.pushButton_clear_list.setText(_translate("DialogLoadCg6ObservationFiles", "Clear list"))
